---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    - topics:
      - "Requirements"
      - "Ansible"
      - "Ansible - Test Driven"
      - "Ansible - Infrastructure vs Project"
  tasks:
    - name: Describe this session
      with_items: topics
      debug: msg="{{ item }}"
