---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    - presenter:
        name: Mark Kusch
        mail: kraM@silpion.de
        notes: I have no idea what I am doing
  tasks:
    - name: Tell the world who I am
      debug: msg="I am {{ presenter.name }} <{{ presenter.mail }}>"
